site_name: Ball Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Hosting: hosting/index.md
  - Hosting (Railway): hosting/railway/index.md
  - Hosting (Heroku): hosting/heroku/index.md
  - Hosting (Replit): hosting/replit
